ALTER TABLE contact_requests
  ADD COLUMN IF NOT EXISTS request_type VARCHAR(30) NOT NULL DEFAULT 'contact',
  ADD COLUMN IF NOT EXISTS organization VARCHAR(300) NULL,
  ADD COLUMN IF NOT EXISTS district VARCHAR(150) NULL,
  ADD COLUMN IF NOT EXISTS responsible_name VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS responsible_phone VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS beneficiary_name VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS beneficiary_phone VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS attachments JSONB NULL;