ALTER TABLE patients
  ADD COLUMN IF NOT EXISTS benefits_status VARCHAR(30),
  ADD COLUMN IF NOT EXISTS urgent_needs TEXT,
  ADD COLUMN IF NOT EXISTS needs_resolution_stage VARCHAR(30),
  ADD COLUMN IF NOT EXISTS is_pdn BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS pdn_details TEXT,
  ADD COLUMN IF NOT EXISTS is_sop BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS sop_details TEXT;
